In [ ]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [13]:
revenues = [120, 250, 80, 310, 95]
revenue_after_tax=[]
for value in revenues:
    revenue_after_tax.append(value*1.18)
    revenue_after_tax

In [14]:
print(revenue_after_tax)

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [15]:
revenue_after_tax
discount_rate = 0.10
revenue_after_discount=[]
revenue_after_discount=[value*(1-discount_rate) for value in revenue_after_tax]
print(revenue_after_discount)

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [23]:
revenue_after_discount
for value in revenue_after_discount:
    if value>100:
        print(True)
    else:
        print(False)

True
True
False
True
True

In [25]:
revenue_after_discount
for value in revenue_after_discount:
    if value>100 and value<200:
        print(True)
    elif value>200 and  value<300:
        print(True)
    else:
        print(False)

True
True
False
False
True

In [26]:
sales = [120, 250, 80, 310, 95]
avg_sales=(sum(sales)/len(sales))
print(avg_sales)

171.0

In [27]:
sales = [120, 250, 80, 310, 95]

highest = sales[0]
for s in sales:
    if s > highest:
        highest = s
print(highest)

310

In [31]:
len(sales)

5

In [33]:
sales
for value in sales:
    if value > 150:
        print(len(sales))

5
5

In [37]:
sales
count=sum(1 for s in sales if s > 150)
print(count)

2

In [38]:
sales
revenue=[]
c=0.05
revenue=[value*(1+c)for value in sales]
print(revenue)

[126.0, 262.5, 84.0, 325.5, 99.75]

In [40]:
revenue
for v in revenue:
    if v > 250:
        print("Premium",v)
    elif 100< v <= 250:
        print("Standard",v)
    else:
        print("Low",v)

Standard 126.0
Premium 262.5
Low 84.0
Premium 325.5
Low 99.75

In [43]:
labels_segment=["Standard","Premium","Low","Premium","Low"]

In [48]:
premium_count = labels_segment.count("Premium")
print(premium_count)

2

In [49]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

In [50]:
len(customer_ids)

8

In [51]:
set(customer_ids)

{1, 2, 3, 4, 5, 6}

In [53]:
len(set(customer_ids))

6

In [54]:
list(set(customer_ids))

[1, 2, 3, 4, 5, 6]

In [55]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

In [56]:
customer["segment"]="Premium"
print(customer)

{'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'Premium'}

In [57]:
customer["revenue"]=300
print(customer)

{'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'Premium'}

In [58]:
del customer["city"]
print(customer)

{'name': 'Anna', 'revenue': 300, 'segment': 'Premium'}

In [59]:
for key in customer:
    print(key,customer[key])

name Anna
revenue 300
segment Premium

In [60]:
revenues = [120, 250, 80, 310, 95]
taxed_revenue=[r*0.9 for r in revenues]
print (taxed_revenue)

[108.0, 225.0, 72.0, 279.0, 85.5]

In [61]:
filtered_revenue=[r for r in revenues if r>100]
print(filtered_revenue)

[120, 250, 310]

In [62]:
labaled_revenue=["High" if r>200 else "Normal" for r in revenues]

In [63]:
print(labaled_revenue)

['Normal', 'High', 'Normal', 'High', 'Normal']

In [64]:
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [67]:
t = 0.18
df["revenue_after_tax"] = df["revenue"] * (1 +t)
df

   revenue  revenue_after_tax
0      120              141.6
1      250              295.0
2       80               94.4
3      310              365.8
4       95              112.1

In [70]:
df.loc[df["revenue_after_tax"]>150,"segment"]="High"
df.loc[df["revenue_after_tax"]<150,"segment"]="Low"
df

   revenue  revenue_after_tax segment
0      120              141.6     Low
1      250              295.0    High
2       80               94.4     Low
3      310              365.8    High
4       95              112.1     Low

In [72]:
df[df["revenue_after_tax"]>100]

   revenue  revenue_after_tax segment
0      120              141.6     Low
1      250              295.0    High
3      310              365.8    High
4       95              112.1     Low

In [75]:
df.drop("segment",axis=1)

   revenue  revenue_after_tax
0      120              141.6
1      250              295.0
2       80               94.4
3      310              365.8
4       95              112.1