In [1]:
import pandas as pd

In [2]:
import numpy as np

In [1]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

In [9]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [10]:
data = {
    "customer": ["Anna", "David", "Liza"],
    "revenue": [100, 250, 180]
}

df = pd.DataFrame(data)
df

  customer  revenue
0     Anna      100
1    David      250
2     Liza      180

In [11]:
import pandas as pd

df_orders = pd.read_csv("../data/raw/orders.csv")
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [12]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [14]:
del zip_ref

In [15]:
df_orders.rename(columns={'order_n': 'order_number'})

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [16]:
type(df_orders.head())

pandas.DataFrame

In [17]:
shape = df_orders.shape
type(shape)

tuple

In [18]:
if df_orders.shape[0] > 1000000:
    print('DANGER')
else:
    print('OKAY')

DANGER

In [19]:
print(type(df_orders.shape))
print(f" The # of rows: {df_orders.shape[0]} \n The # of columns: {df_orders.shape[1]}")

<class 'tuple'>
 The # of rows: 3421083
 The # of columns: 7

In [20]:
## List of column
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [21]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [22]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [23]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [24]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [25]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [26]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [27]:
df_orders.drop(columns = ['eval_set'], inplace = True)

In [30]:
df_orders_new = df_orders.assign(
    is_weekend = df_orders["order_dow"].isin([0, 6]),
    is_morning = df_orders["order_hour_of_day"] < 12,
    # is_premium = df_orders["days_since_prior_order"] <= 7
)

In [31]:
df_orders_new['days_since_prior_order'] = df_orders_new['days_since_prior_order'].fillna(0)

In [32]:
df_orders_new.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning
0,2539329,1,1,2,8,0.0,False,True
1,2398795,1,2,3,7,15.0,False,True
2,473747,1,3,3,12,21.0,False,False
3,2254736,1,4,4,7,29.0,False,True
4,431534,1,5,4,15,28.0,False,False

In [33]:
df_orders_new.to_csv('../data/processed/order.csv', index = False)

In [34]:
df_products.drop(columns=['aisle_id'],inplace=True)

In [35]:
df_departments = pd.read_csv('../data/raw/departments.csv')

In [36]:
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [37]:
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [38]:
df_temp_t = df_departments.T
df_temp_t.head()

                        0
department_id  department
1                  frozen
2                   other
3                  bakery
4                 produce

In [39]:
df_temp_t.info()

<class 'pandas.DataFrame'>
Index: 22 entries, department_id to 21
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       22 non-null     str
dtypes: str(1)
memory usage: 908.0+ bytes

In [40]:
df_products.reset_index()

,index,product_id,product_name,department_id,prices
0,0,1,Chocolate Sandwich Cookies,19,5.8
1,1,2,All-Seasons Salt,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.5
4,4,5,Green Chile Anytime Sauce,13,4.3
...,...,...,...,...,...
49688,49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",5,5.3
49689,49689,49685,En Croute Roast Hazelnut Cranberry,1,3.1
49690,49690,49686,Artisan Baguette,3,7.8
49691,49691,49687,Smartblend Healthy Metabolism Dry Cat Food,8,4.7
49692,49692,49688,Fresh Foaming Cleanser,11,13.5

In [41]:
df_temp_t.reset_index(inplace=True)

In [42]:
df_temp_t.head()

           index           0
0  department_id  department
1              1      frozen
2              2       other
3              3      bakery
4              4     produce

In [43]:
col_names = df_temp_t.iloc[0]
col_names

index    department_id
0           department
Name: 0, dtype: str

In [44]:
department_main_data = df_temp_t.iloc[1:]
department_main_data.head()

  index        0
1     1   frozen
2     2    other
3     3   bakery
4     4  produce
5     5  alcohol

In [45]:
department_main_data.columns = col_names

In [46]:
department_main_data.head()

0 department_id department
1             1     frozen
2             2      other
3             3     bakery
4             4    produce
5             5    alcohol

In [47]:
department_main_data.reset_index(inplace=True)

In [48]:
department_main_data.head()

0  index department_id department
0      1             1     frozen
1      2             2      other
2      3             3     bakery
3      4             4    produce
4      5             5    alcohol

In [49]:
df_products.to_csv("../data/processed/products_cleaned.csv", index=False)

In [56]:
df_dep_t_new=department_main_data

In [58]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0