In [3]:
import pandas as pd

In [37]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [38]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [39]:
df_orders["order_id"].nunique()

3421083

In [40]:
if df_orders['order_id'].nunique==df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Sad

In [8]:
df_orders['order_id'].nunique()/df_orders['user_id'].nunique()

16.590367054784224

In [41]:
df_orders["user_id"].nunique()

206209

In [42]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [43]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='object')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [44]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [45]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['index', 'department_id', 'department'], dtype='object')
(21, 3)

   index  department_id department
0      1              1     frozen
1      2              2      other
2      3              3     bakery
3      4              4    produce
4      5              5    alcohol

In [14]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='object')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [46]:
df_dow=df_orders['order_dow'].value_counts().reset_index().sort_values('order_dow')

In [47]:
print(df_dow)

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

In [48]:
df_dow.to_csv('../data/processed/dow.csv',index=False)

In [49]:
df_ohod=df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [50]:
df_ohod.to_excel('../data/processed/ohod.xlsx',index=False)

In [51]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [21]:
needed_columns=['days_since_prior_order','order_number','user_id']

In [22]:
df_orders['order_id'].is_unique

True

In [23]:
del df_orders

In [24]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1    0.598594
0    0.401406
Name: proportion, dtype: float64

In [25]:
df_orders_products_train["add_to_cart_order"].describe()

count    1.384617e+06
mean     8.758044e+00
std      7.423936e+00
min      1.000000e+00
25%      3.000000e+00
50%      7.000000e+00
75%      1.200000e+01
max      8.000000e+01
Name: add_to_cart_order, dtype: float64

In [26]:
df_orders_products_train["add_to_cart_order"].value_counts().sort_index().head(20)

add_to_cart_order
1     131209
2     124364
3     116996
4     108963
5     100745
6      91850
7      83142
8      74601
9      66618
10     59401
11     52848
12     46814
13     41431
14     36588
15     32194
16     28363
17     24841
18     21733
19     19014
20     16541
Name: count, dtype: int64

In [27]:
df_orders_products_train["reordered"].isin([0, 1]).all()

np.True_

In [28]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [29]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  object
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.9+ MB

In [30]:
df_products.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [31]:
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [32]:
df_products[["product_id", "product_name", "aisle_id", "department_id"]].head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [33]:
df_departments.head()

   index  department_id department
0      1              1     frozen
1      2              2      other
2      3              3     bakery
3      4              4    produce
4      5              5    alcohol

In [34]:
df_departments.drop('index',axis=1,inplace=True)

In [52]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.0
25,1492625,2,train,15,1,11,30.0
49,2196797,5,train,5,0,11,6.0
74,525192,7,train,21,2,11,6.0
78,880375,8,train,4,1,14,10.0

In [53]:
del df_orders

In [ ]:
df_orders_products_train[df_orders_products_train['order_id']==1]

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1
5         1       13176                  6          0
6         1       47209                  7          0
7         1       22035                  8          1

In [1]:
df_products_departments_check = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator=True
)

df_products_departments_check.head()

NameError: name 'pd' is not defined

In [55]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,index,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,19,snacks
1,2,All-Seasons Salt,104,13,9.3,13,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,7,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,1,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,13,pantry

In [56]:
df_products_departments_check["_merge"].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [57]:
df_products_departments["department"].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [58]:
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left"
)

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,index,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,19,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,13,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,7,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,1,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,13,pantry,marinades meat preparation

In [59]:
df_products_aisles_check = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left",
    indicator=True
)

df_products_aisles_check["_merge"].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [60]:
print(df_products.shape)
print(df_products_departments.shape)
print(df_products_enriched.shape)

(49693, 5)
(49693, 7)
(49693, 8)

In [61]:
df_departments["department_id"].is_unique

True

In [62]:
df_products_enriched["aisle"].value_counts().head(10)

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
chips pretzels           989
tea                      894
packaged cheese          891
frozen meals             880
cookies cakes            874
Name: count, dtype: int64

In [63]:

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,index,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,19,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,13,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,7,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,1,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,13,pantry,marinades meat preparation

In [64]:
df_train_transactions = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left"
)

df_train_transactions.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.0,196,1,1
1,1187899,1,train,11,4,8,14.0,25133,2,1
2,1187899,1,train,11,4,8,14.0,38928,3,1
3,1187899,1,train,11,4,8,14.0,26405,4,1
4,1187899,1,train,11,4,8,14.0,39657,5,1

In [65]:
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
    indicator=True
)

df_train_transactions_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1187899,1,train,11,4,8,14.0,196,1,1,both
1,1187899,1,train,11,4,8,14.0,25133,2,1,both
2,1187899,1,train,11,4,8,14.0,38928,3,1,both
3,1187899,1,train,11,4,8,14.0,26405,4,1,both
4,1187899,1,train,11,4,8,14.0,39657,5,1,both

In [66]:
df_train_transactions_check["_merge"].value_counts()

_merge
both          1384617
left_only           0
right_only          0
Name: count, dtype: int64

In [67]:
print(df_orders_train.shape)
print(df_orders_products_train.shape)
print(df_train_transactions.shape)

(131209, 7)
(1384617, 4)
(1384617, 10)

In [68]:
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left"
)

df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,index,department,aisle
0,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,7.0,beverages,soft drinks
1,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,16.0,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,16.0,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,17.0,household,paper goods
4,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,19.0,snacks,candy chocolate

In [69]:
df_train_analytic_check = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left",
    indicator=True
)

df_train_analytic_check["_merge"].value_counts()

_merge
both          1384618
left_only          88
right_only          0
Name: count, dtype: int64

In [70]:
df_train_analytic.to_csv("../data/processed/train_analytic_cleaned.csv",index=False)

In [71]:
df_train_analytic.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,index,department,aisle
1384701,272231,206209,train,14,6,14,30.0,40603,4,0,Fabric Softener Sheets,75.0,17.0,1.4,17.0,household,laundry
1384702,272231,206209,train,14,6,14,30.0,15655,5,0,Dark Chocolate Mint Snacking Chocolate,45.0,19.0,2.1,19.0,snacks,candy chocolate
1384703,272231,206209,train,14,6,14,30.0,42606,6,0,Phish Food Frozen Yogurt,37.0,1.0,2.7,1.0,frozen,ice cream ice
1384704,272231,206209,train,14,6,14,30.0,37966,7,0,French Baguette Bread,112.0,3.0,15.0,3.0,bakery,bread
1384705,272231,206209,train,14,6,14,30.0,39216,8,1,Original Multigrain Spoonfuls Cereal,121.0,14.0,3.3,14.0,breakfast,cereal

In [72]:
import pandas as pd
URL_CUSTOMERS='https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv'
URL_STATES= 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv'

In [73]:
URLS={
    'customers.csv': URL_CUSTOMERS,
    'state.csv': URL_STATES
}

In [74]:
for i in URLS.items():
    df=pd.read_csv(i[1])
    df.to_csv(f'../data/raw/{i[0]}')

In [75]:
df_customers=pd.read_csv('../data/raw/customers.csv')

In [76]:
df_customers.head()

,Unnamed: 0,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [ ]:
df_customers.shape

(206209, 11)

In [ ]:
print(df_customers.columns)

Index(['Unnamed: 0', 'user_id', 'First Name', 'Surnam', 'Gender', 'STATE',
       'Age', 'date_joined', 'n_dependants', 'fam_status', 'income'],
      dtype='object')

In [77]:
df_state=pd.read_csv('../data/raw/state.csv')
df_state.head()

   Unnamed: 0          state     region     division
0           0    Connecticut  Northeast  New England
1           1          Maine  Northeast  New England
2           2  Massachusetts  Northeast  New England
3           3  New Hampshire  Northeast  New England
4           4   Rhode Island  Northeast  New England

In [78]:
df_state.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df_customers.drop('Unnamed: 0',axis=1,inplace=True)

In [81]:
df_customers.rename(columns={'STATE':'state'}, inplace=True)

In [82]:
df_customer_location=pd.merge(
df_customers,
df_state,
on='state',
how="left"    
)
df_customer_location.head()

,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,Midwest,West North Central
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,West,Mountain
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,West,Mountain
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,Midwest,West North Central
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,South,South Atlantic

In [83]:
df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,index,department,aisle
0,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,7.0,beverages,soft drinks
1,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,16.0,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,16.0,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,17.0,household,paper goods
4,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,19.0,snacks,candy chocolate

In [84]:
df_sales_analytic=pd.merge(
    df_train_analytic,
    df_customer_location,
    on="user_id",
    how="left"
)
df_sales_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,1,train,11,4,8,14.0,196,1,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,1,train,11,4,8,14.0,25133,2,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,1,train,11,4,8,14.0,38928,3,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,1,train,11,4,8,14.0,26405,4,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,1,train,11,4,8,14.0,39657,5,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [85]:
print(df_sales_analytic.columns)

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'index', 'department', 'aisle', 'First Name',
       'Surnam', 'Gender', 'state', 'Age', 'date_joined', 'n_dependants',
       'fam_status', 'income', 'region', 'division'],
      dtype='object')

In [86]:
df_sales_analytic['state'].value_counts().head(10)

state
Arkansas        28772
Illinois        28460
New Jersey      28113
California      28091
Indiana         27769
Wyoming         27767
Kentucky        27756
Virginia        27708
North Dakota    27699
Missouri        27678
Name: count, dtype: int64

In [87]:
df_sales_analytic.shape

(1384706, 28)

In [88]:
df_sales_analytic.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,aisle_id,department_id,prices,index,Age,n_dependants,income
count,1.384706e+06,1.384706e+06,1.384706e+06,1.384706e+06,1.384706e+06,1.384706e+06,1.384706e+06,1.384706e+06,1.384706e+06,1.384618e+06,1.384618e+06,1.384618e+06,1.384618e+06,1.384706e+06,1.384706e+06,1.384706e+06
mean,1.706298e+06,1.031121e+05,1.709135e+01,2.701394e+00,1.357761e+01,1.706626e+01,2.555658e+04,8.758180e+00,5.985964e-01,7.130659e+01,9.840116e+00,1.411711e+01,9.840116e+00,4.938182e+01,1.498778e+00,9.766228e+04
std,9.897342e+05,5.948753e+04,1.661400e+01,2.167637e+00,4.238461e+00,1.042639e+01,1.412097e+04,7.423973e+00,4.901825e-01,3.810535e+01,6.292848e+00,6.802253e+02,6.292848e+00,1.843685e+01,1.117567e+00,4.199139e+04
min,1.000000e+00,1.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.800000e+01,0.000000e+00,2.591100e+04
25%,8.433700e+05,5.173200e+04,6.000000e+00,1.000000e+00,1.000000e+01,7.000000e+00,1.338000e+04,3.000000e+00,0.000000e+00,3.100000e+01,4.000000e+00,4.300000e+00,4.000000e+00,3.300000e+01,0.000000e+00,6.485900e+04
50%,1.701880e+06,1.029330e+05,1.100000e+01,3.000000e+00,1.400000e+01,1.500000e+01,2.530000e+04,7.000000e+00,1.000000e+00,8.300000e+01,8.000000e+00,7.400000e+00,8.000000e+00,4.900000e+01,1.000000e+00,9.576500e+04
75%,2.568023e+06,1.549590e+05,2.100000e+01,5.000000e+00,1.700000e+01,3.000000e+01,3.794000e+04,1.200000e+01,1.000000e+00,1.070000e+02,1.600000e+01,1.130000e+01,1.600000e+01,6.500000e+01,2.000000e+00,1.268178e+05
max,3.421070e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01,4.968800e+04,8.000000e+01,1.000000e+00,1.340000e+02,2.100000e+01,9.999900e+04,2.100000e+01,8.100000e+01,3.000000e+00,5.910890e+05

In [89]:
df_sales_analytic['prices'].mean()

np.float64(14.117111001012553)

In [90]:
df_sales_analytic.isna().sum()

order_id                      0
user_id                       0
eval_set                      0
order_number                  0
order_dow                     0
order_hour_of_day             0
days_since_prior_order        0
product_id                    0
add_to_cart_order             0
reordered                     0
product_name               1233
aisle_id                     88
department_id                88
prices                       88
index                        88
department                   88
aisle                        88
First Name                75432
Surnam                        0
Gender                        0
state                         0
Age                           0
date_joined                   0
n_dependants                  0
fam_status                    0
income                        0
region                        0
division                      0
dtype: int64

In [91]:
print(df_sales_analytic.columns)

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'index', 'department', 'aisle', 'First Name',
       'Surnam', 'Gender', 'state', 'Age', 'date_joined', 'n_dependants',
       'fam_status', 'income', 'region', 'division'],
      dtype='object')

In [92]:
df_train_analytics_final = df_sales_analytic

In [93]:
df_train_analytics_final.drop(columns=['user_id','eval_set','product_id', 'aisle_id', 'department_id'],inplace=True)

In [94]:
print(df_train_analytics_final.shape)
df_train_analytics_final.head()

(1384706, 23)

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,index,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,11,4,8,14.0,1,1,Soda,9.0,7.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,16.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,16.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,17.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,19.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [95]:
df_train_analytics_final.to_parquet("../data/processed/instacart.parquet", index = False)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_instacart = pd.read_parquet("../data/processed/instacart.parquet")
df_instacart.head()

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,index,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,11,4,8,14.0,1,1,Soda,9.0,7.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,16.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,16.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,17.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,19.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central